### ISSUE TITLE
DDOS - Jeremy Martini

### ISSUE THREAD

**Issue by Adversities** [JavaNigga/Note.io#3]
Hola, soy un programador de Venezuela... yo he sido quien ha estado enviando sin parar las solicitudes masivas para crear cartas...

Primero que nada, disculpa... no era mi intención "ddosear", mi idea era llamar tu atención para que me contactaras por Discord y ahí explicarte como mejorar tu app (que esta muy bien)... Mi Discord: Adversities#6310

El "ataque"
Lo que hago es mandar una solicitud HttpPost a https://noteioserver.herokuapp.com/CC?losDatos={json} o https://noteioserver.herokuapp.com/CrearCarta?losDatos={json}, no tiene ningún tipo de checksum, captcha, tiempo por solicitud, nada...

**Solución A:** Limitar el número de respuestas por tiempo, si este usuario (desde esta IP) hizó 4 solicitudes seguidas y va a hacer la quinta en menos de 20 segundos, bloquearlo hasta que pasen 20 segundos (para esa IP)

**Solucion B:** Captcha (a mi no me atrae mucho, seguro a ti tampoco), en el query "losDatos" podrías agregar un campo "checksum" donde pondrás el hash generado por el captcha. (ej, [Captcha de Google](https://developers.google.com/recaptcha/))

**Solución C:** generar tokens para cada solicitud, un usuario obtendrá un token diferente cada vez que haga una solicitud, dicho token no debe estar visible en ningún lugar de la página, ni debe viajar al lado cliente sin seguridad extra (un poco mas complicado)

_Yo personalmente optaría por la solución A_

**Comment by MerliMejia** [comment]
Hola, ya te envie una solicitud al discord, por favor aceptala y discutamos por ahi. Muchas gracias

**Comment by Adversities** [comment]
Por cierto tengo una idea para tu proyecto, en el json de crear cartas envía también una propiedad "color" y generalo con una función random que vaya desde 0 hasta 16777215, luego eso lo conviertes a hexadecimal y ya tienes colores randoms para cada carta...

**Comment by Adversities** [comment]
Gracias por prestar atención y aplicar una de las soluciones recomendadas
